Repository INNER-CIRCLE-ICD4/Project-3.-Commerce, pull requests merged in 2025-07, with the labels that each got.

#8 #7 git strategy
  .github/PULL_REQUEST_TEMPLATE.md
  docs/git-branch-strategy.md
Labels: documentation

#9 feat: 프로젝트 초기화
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle.kts
  common/snowflake/build.gradle.kts
  common/snowflake/src/main/java/innercircle/commerce/common/snowflake/Snowflake.java
  common/snowflake/src/test/java/innercircle/commerce/common/snowflake/SnowflakeTest.java
  docs/snowflake.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  service/order/build.gradle.kts
  service/order/src/main/java/innercircle/commerce/order/OrderApplication.java
  service/order/src/main/resources/application.yml
  service/product/build.gradle.kts
  service/product/src/main/java/innercircle/commerce/product/ProductApplication.java
  service/product/src/main/resources/application.yml
  service/review/build.gradle.kts
  service/review/src/main/java/innercircle/commerce/review/ReviewApplication.java
  service/review/src/main/resources/application.yml
  service/search/build.gradle.kts
  service/search/src/main/java/innercircle/commerce/search/SearchApplication.java
  service/search/src/main/resources/application.yml
  settings.gradle.kts
Labels: docs, feat

#11 10 chore commerce cicd
  .github/workflows/e-commerce_actions.yaml
  common/snowflake/build.gradle.kts
  service/order/Dockerfile
  service/product/Dockerfile
  service/review/Dockerfile
  service/review/src/main/java/innercircle/commerce/review/Review.java
  service/review/src/main/java/innercircle/commerce/review/ReviewApplication.java
  service/review/src/main/java/innercircle/commerce/review/ReviewController.java
  service/search/Dockerfile
Labels: chore

#24 feature(gateway): Spring Cloud Gateway 설정 및 테스트
  infra/gateway/build.gradle.kts
  infra/gateway/src/main/resources/application.yml
  infra/gateway/src/main/resources/gateway.http
  service/review/src/main/java/innercircle/commerce/review/ReviewController.java
  service/review/src/main/resources/application.yml
Labels: feat

#30 22 msa infra 모듈 cicd 적용 및 cicd 개선
  .github/workflows/e-commerce-infra_actions.yaml
  .github/workflows/e-commerce-service_actions.yaml
  .github/workflows/e-commerce_actions.yaml
  common/snowflake/src/main/java/innercircle/commerce/common/snowflake/Snowflake.java
  infra/config-server/Dockerfile
  infra/config-server/src/main/java/innercircle/configserver/ConfigServerApplication.java
  infra/config-server/src/main/java/innercircle/configserver/config/JasyptConfig.java
  infra/eureka-server/Dockerfile
  infra/eureka-server/src/main/java/innercircle/eurekaserver/EurekaServerApplication.java
  infra/gateway/Dockerfile
  infra/gateway/src/main/java/commerce/gateway/GatewayApplication.java
  settings.gradle.kts
Labels: chore

#27 25 feature member
  service/member/build.gradle.kts
  service/member/src/main/java/innercircle/member/MemberApplication.java
  service/member/src/main/java/innercircle/member/application/BCryptPasswordEncoderAdapter.java
  service/member/src/main/java/innercircle/member/application/MemberCreateRequest.java
  service/member/src/main/java/innercircle/member/application/MemberResponse.java
  service/member/src/main/java/innercircle/member/application/MemberService.java
  service/member/src/main/java/innercircle/member/application/MemberUseCase.java
  service/member/src/main/java/innercircle/member/application/PasswordEncoderPort.java
  service/member/src/main/java/innercircle/member/domain/BaseEntity.java
  service/member/src/main/java/innercircle/member/domain/Email.java
  service/member/src/main/java/innercircle/member/domain/Gender.java
  service/member/src/main/java/innercircle/member/domain/Member.java
  service/member/src/main/java/innercircle/member/domain/MemberDomainService.java
  service/member/src/main/java/innercircle/member/domain/MemberRepository.java
  service/member/src/main/java/innercircle/member/domain/MemberStatus.java
  service/member/src/main/java/innercircle/member/domain/SnowFlakeGenerator.java
  service/member/src/main/java/innercircle/member/domain/ValidationMember.java
  service/member/src/main/java/innercircle/member/infrastructure/MemberJpaRepository.java
  service/member/src/main/java/innercircle/member/infrastructure/MemberJpaRepositoryAdapter.java
  service/member/src/main/resources/application.yml
  service/member/src/test/java/innercircle/member/MemberApplicationTests.java
  service/member/src/test/java/innercircle/member/application/BCryptPasswordEncoderAdapterTest.java
  service/member/src/test/java/innercircle/member/application/MemberServiceTest.java
  service/member/src/test/java/innercircle/member/domain/MemberDomainServiceTest.java
  service/member/src/test/java/innercircle/member/domain/MemberRepositoryTest.java
  service/member/src/test/java/innercircle/member/domain/MemberTest.java
  settings.gradle.kts
Labels: feat
